__KNOWN__: dict = {
    '^int' : 'superscript-int',
    '<greekLetter>' : 'greekLetter',
    '<greekLetter-lower>' : 'greekLetter-lower',
    '<integral-symbol-name>' : 'integral-symbol',
    '<set-theory-symbol-name>' : 'set-theory-symbol',
    '<subscript-i>' : 'ᵢ',
    '<sub-i>' : 'ᵢ',
    '!=' : '≠',
    '<sqrt>' : '√',
    '<x-bar>' : 'x̄',
    '<inf>' : '∞',
    '*' : '⋅'
}

__POWERS__: dict = {
    '^1' : '¹',
    '^2' : '²',
    '^3' : '³',
    '^4' : '⁴',
    '^5' : '⁵',
    '^6' : '⁶',
    '^7' : '⁷',
    '^8' : '⁸',
    '^9' : '⁹'
}

__SUPERSCRIPT__: dict = {
    'a': 'ᵃ',
    'b': 'ᵇ',
    'c': 'ᶜ',
    'd': 'ᵈ',
    'e': 'ᵉ',
    'f': 'ᶠ',
    'g': 'ᵍ',
    'h': 'ʰ',
    'i': 'ⁱ',
    'j': 'ʲ',
    'k': 'ᵏ',
    'l': 'ˡ',
    'm': 'ᵐ',
    'n': 'ⁿ',
    'o': 'ᵒ',
    'p': 'ᵖ',
    'q': '𐞥',
    'r': 'ʳ',
    's': 'ˢ',
    't': 'ᵗ',
    'u': 'ᵘ',
    'v': 'ᵛ',
    'w': 'ʷ',
    'x': 'ˣ',
    'y': 'ʸ',
    'z': 'ᶻ',
    'A': 'ᴬ',
    'B': 'ᴮ',
    'C': 'ᶜ',
    'D': 'ᴰ',
    'E': 'ᴱ',
    'F': 'ᶠ',
    'G': 'ᴳ',
    'H': 'ᴴ',
    'I': 'ᴵ',
    'J': 'ᴶ',
    'K': 'ᴷ',
    'L': 'ᴸ',
    'M': 'ᴹ',
    'N': 'ᴺ',
    'O': 'ᴼ',
    'P': 'ᴾ',
    'Q': 'ꟴ',
    'R': 'ᴿ',
    'S': 'ˢ',
    'T': 'ᵀ',
    'U': 'ᵁ',
    'V': 'ⱽ',
    'W': 'ᵂ',
    'X': 'ˣ',
    'Y': 'ʸ',
    'Z': 'ᶻ',
    '1' : '¹',
    '2' : '²',
    '3' : '³',
    '4' : '⁴',
    '5' : '⁵',
    '6' : '⁶',
    '7' : '⁷',
    '8' : '⁸',
    '9' : '⁹',
    '+' : '⁺',
    '-' : '⁻',
    '(' : '⁽',
    ')' : '⁾',
    ' ' : ' ',
    '*' : '*'
}
__SUPERSCRIPT_GREEK_LETTERS__ = {
    '<alpha-lower>' : 'ᵅ',
    '<beta-lower>' : 'ᵝ',
    '<gamma-lower>' : 'ᵞ',
    '<delta-lower>' : 'ᵟ',
    '<epsilon-lower>' : 'ᵋ',
    '<zeta-lower>' : 'ᶿ',
    '<eta-lower>' : 'ᶥ',
    '<theta-lower>' : 'ᶲ',
    '<iota-lower>' : 'ᵠ',
    '<kappa-lower>' : 'ᵡ'
}

__GREEK__: dict = {
    '<alpha>' : 'Α',
    '<alpha-lower>': 'α',
    '<beta>' : 'Β',
    '<beta-lower>': 'β',
    '<gamma>' : 'Γ',
    '<gamma-lower>': 'γ',
    '<delta>' : 'Δ',
    '<delta-lower>': 'δ',
    '<epsilon>' : 'Ε',
    '<epsilon-lower>': 'ε',
    '<zeta>' : 'Ζ',
    '<zeta-lower>': 'ζ',
    '<eta>' : 'Η',
    '<eta-lower>': 'η',
    '<theta>' : 'Θ',
    '<theta-lower>': 'θ',
    '<iota>' : 'Ι',
    '<iota-lower>': 'ι',
    '<kappa>' : 'Κ',
    '<kappa-lower>': 'κ',
    '<lambda>' : 'Λ',
    '<lambda-lower>': 'λ',
    '<mu>' : 'Μ',
    '<mu-lower>': 'μ',
    '<nu>' : 'Ν',
    '<nu-lower>': 'ν',
    '<xi>' : 'Ξ',
    '<xi-lower>': 'ξ',
    '<omicron>' : 'Ο',
    '<omicron-lower>': 'ο',
    '<pi>' : 'Π',
    '<pi-lower>': 'π',
    '<rho>' : 'Ρ',
    '<rho-lower>': 'ρ',
    '<sigma>' : 'Σ',
    '<sigma-lower>': 'σ',
    '<tau>' : 'Τ',
    '<tau-lower>': 'τ',
    '<upsilon>' : 'Υ',
    '<upsilon-lower>': 'υ',
    '<phi>' : 'Φ',
    '<phi-lower>': 'φ',
    '<chi>' : 'Χ',
    '<chi-lower>': 'χ',
    '<psi>' : 'Ψ',
    '<psi-lower>': 'ψ',
    '<omega>' : 'Ω',
    '<omega-lower>': 'ω'
}
__INTEGRALS__: dict = {
    '<summation-with-integral>' : '⨋',
    '<integral>' : '∫',
    '<double-integral>' : '∬',
    '<tripple-integral>' : '∭',
    '<quadruple-integral>' : '⨌',
    '<finite-part-integral>' : '⨍',
    '<integral-with-double-stroke>' : '⨎',
    '<integral-average-with-slash>' : '⨏',
    '<integral-around-a-point>' : '⨕',
    '<quaternion-integral>' : '⨖',
    '<integral-with-leftwards-arrow-with-hook>' : '⨗',
    '<integral-with-times-sign>' : '⨘',
    '<integral-with-intersection>' : '⨙',
    '<integral-with-union>' : '⨚',
    '<integral-with-overderbar>' : '⨛',
    '<integral-with-underbar>' : '⨜'
}

__COMPARE__: dict = {
    '<divide>' : '÷',
    '<=' : '≤',
    '>=' : '≥',
    '!=' : '≠',
    'aprox/' : '≈',
    '<aprox>' : '≈',
    '<approximately>' : '≈',
    '<union>' : '∪',
    '<intersection>' : '∩',
    '<intersect>' : '∩',
    '<subset>' : '⊂',
    '<belongs>' : '∈',
    '<belongs-to>' : '∈',
    '<strict-superset-set>' : '⊃',
    '<superset-set>' : '⊇',
    '<not-subset>' : '⊈',
    '<not-belongs-to>' : '∉',
    '<empty-set>' : 'Ø'
}
__REPLACE__: dict = {
    '<x-bar>' : 'x̄',
    '<sqrt>' : '√',
    '<infinity>' : '∞',
    '<inf>' : '∞',
    '<subscript-i>' : 'ᵢ',
    '<sub-i>' : 'ᵢ',
    '*' : '⋅'
}
# __REPLACE__.update(__POWERS__)
__REPLACE__.update(__GREEK__)
__REPLACE__.update(__INTEGRALS__)
__REPLACE__.update(__COMPARE__)